### ISSUE TITLE
Player Arrows on Minimap

### ISSUE THREAD

**Issue by Whatsatotem** [Wutname1/SpartanUI#95] opened 2018-09-06 19:24 UTC
Requested by Tweenkie (Discord)
When players are out of range on the minimap (cant confirm if one or multiple styles) the arrows that point you towards another player doesn't show up. 

i noticed it this week in island expeditions

**Comment by Wutname1** [comment] 2018-09-11 02:35
What style is this occurring on? I cannot reproduce.

**Comment by Whatsatotem** [comment] 2018-09-11 03:00
it appears Tweenkie has left discord...

**Comment by Wutname1** [comment] 2018-09-11 03:26
I just did a few Warfronts and i saw the arrows.

**Comment by Wutname1** [comment] 2018-09-13 19:13
Closing until the issue pops back up with more info.

**Closed by Wutname1** 2018-09-13 19:13 UTC
Labels: Need more info
