### ISSUE TITLE
Autovendor not working[Wrath Bug Report]

### ISSUE THREAD

**Issue by A-Wolfheart** [Wutname1/SpartanUI#491] opened 2023-01-22 22:08 UTC
**Describe the bug**
AutoVendor is not selling grays and giving me a message saying none are available to sell

**To Reproduce**

**Screenshots**

**Game details:**

- Disabled Modules:

**Additional context**

**Comment by Arkanae666** [comment] 2023-02-04 16:38
Good evening Everyone

The error as follows:

Date: 2023-02-04 16:27:44
ID: 1
Error occured in: Global
Count: 1
Message: Interface/AddOns/SpartanUI/Themes/Fel/Style.lua line 177:
   attempt to index field 'Minimap' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "@Interface/AddOns/SpartanUI/Themes/Fel/Style.lua"]:177: MiniMap()
   [string "@Interface/AddOns/SpartanUI/Themes/Fel/Style.lua"]:161: EnableArtwork()
   [string "@Interface/AddOns/SpartanUI/Themes/Fel/Style.lua"]:97:
      Interface/AddOns/SpartanUI/Themes/Fel/Style.lua:93
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Attune/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:66:
      ...ace/AddOns/Attune/Libs/AceAddon-3.0/AceAddon-3.0.lua:61
   [string "@Interface/AddOns/Attune/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: EnableAddon()
   [string "@Interface/AddOns/Attune/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:536: EnableAddon()
   [string "@Interface/AddOns/Attune/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:626:
      ...ace/AddOns/Attune/Libs/AceAddon-3.0/AceAddon-3.0.lua:611
Locals:
None
AddOns:
  Swatter, v3.4.6921 (SwimmingSeadragon)
  AtlasLootClassic, vv3.1.1
  AtlasLootClassicData, vv3.1.1
  AtlasLootClassicDungeonsAndRaids, vv3.1.1
  Attune, v311
  AucAdvanced, v3.4.6931 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6941 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6928 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6913 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6910 (SwimmingSeadragon)
  AucStatSimple, v3.4.6911 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6912 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6914 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v10.0.16
  BagnonItemLevel, v2.0.67-Release
  Bartender4, v4.14.7
  BeanCounter, v3.4.6933 (SwimmingSeadragon)
  DBMCore, vd98b338
  DBMSpellTimers, vr145
  DBMStatusBarTimers, vd98b338
  DBMVPVEM, v3c03207
  Decursive, v2.7.8.13
  Details, v#Details.DF.Wrath.10410.148
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Enchantrix, v3.4.6942 (SwimmingSeadragon)
  EnchantrixBarker, v3.4.6917 (SwimmingSeadragon)
  FarmingBar, vv3.8.0
  GatherMate2, v1.47-classic
  GatherMate2GasClouds, v1.4
  GearQuipperTBC, v51
  GTFO, v5.0.4
  LeatrixMaps, v3.0.102
  LootReserve, v2023-01-28
  NovaWorldBuffs, v2.44
  Questie, v7.4.11
  RaidBuffTracker, v3.01
  RareScanner, v3.4.1
  SlideBar, v3.4.6919 (SwimmingSeadragon)
  SpartanUI, v6.2.4-Classic
  Spy, v3.1.2
  Stubby, v3.4.6920 (SwimmingSeadragon)
  totalRP3, v2.4.4
  totalRP3Data, v2.4.4
  WeakAuras, v5.3.7
  WeakAurasCompanion, v4.1.0
  BlizRuntimeLib_enUS v3.4.1.30401 <none>
  (ck=62e)

![image](https://user-images.githubusercontent.com/124454636/216778511-c906888d-ff97-4fe0-9e95-e43e990a17d1.png)

Since last and obvious addon update I have been facing this error.

There is no need for any interaction to reproduce this error. A simple /reload ui triggers it.

As the previous fellow stated the autosell function is not working, in any sort of manner. (Obviously, I made sure everything is enabled)

Also, the vehicle interface moves the minimap back to it's original UI position (which i don't know if it is intended or not AND the button for leaving the vehicle doesn't not appear ( it might appear if you /reload ui, already faced several times that it didn't )

If needed any more clarification please don't hesitate in contacting.

Cheers
Ark

**Comment by Summersisle** [comment] 2023-02-07 17:39
I have done some testing on this. On a level 1 character with only the optional SpartanUI modules enabled, and no other mods enabled besides Bartender.

The following items are in my bag
https://www.wowhead.com/wotlk/item=5635/sharp-claw
https://www.wowhead.com/wotlk/item=3676/slimy-ichor
https://www.wowhead.com/wotlk/item=43852/thick-fur-clothing-scraps
https://www.wowhead.com/wotlk/item=5212/blazing-wand

All options are selected in AutoSell and the Maximum iLVL to sell is set to 500

![image](https://user-images.githubusercontent.com/25886892/217308673-4b6e5cf3-cfb9-445b-a910-71c32904e444.png)

Interacting with Barkeep Morag in Orgrimmar SpartanUI shows No items are to be auto sold.

I turned on debug mode but nothing else was shown.

After some digging into the code I changed line 417 in AutoSell.lua. Removing the Retail check and the elseif
`if itemInfo and module:IsSellable(itemInfo.itemID, itemInfo.hyperlink, bag, slot) then`

and it sold all the items except for the Sharp Claw which is a crafting item so it wouldn't be sold.

**Comment by Wutname1** [comment] 2023-03-08 02:19
This is now fixed in 6.2.5, looks like blizz updated wrath to use the DF vendor backend.

**Closed by Wutname1** 2023-03-08 02:19 UTC
Labels: bug, Wrath
