### ISSUE TITLE
Party frame bug + Quest module bug + Main and target frame

### ISSUE THREAD

**Issue by siberia60** [Wutname1/SpartanUI#331] opened 2020-10-15 15:44 UTC
Hello,

I'm back. :D From 2 years ago.

I absolutley love Spartan UI and I want to keep using here.

Here is a couple of bugs I've encoutnered so far. (Beside those already reported.)

1. Party frame.
Party frames are sitting on top of eachother, in such a way that party frame 1 (Player) overlaps the name of Party Frame 2, that overlaps the name of Party Frame 3, etc.

2. Quest Module.
The "Hide in combat" function dosn't work. The quest objective tracker is still visible even if the settings are corectly done.

3. Main target and target frame overlap with the map (in the middle). I've moved them, but thought you should know.

4. I checked this on my paladin, but in the War artwork (The one that sets the Aura bar and char, options, guild, etc buttons on the top + bags) dosn't show all or any of the buttons.

5. Zone ability / special ability button movers don't move the buttons. Even if I do drag them off the middle of the map, the buttons will apear still there.

**Comment by mascotkid** [comment] 2020-10-15 16:13
In addition to the party frames sitting on each other, buffs and debuffs don't show, When trying to set them in the interface, getting this error:

Message: ...face\AddOns\SpartanUI\modules\UnitFrames\Options-Options.lua:1880: attempt to index global 'filters' (a nil value)
Time: Thu Oct 15 12:11:23 2020
Count: 1
Stack: ...face\AddOns\SpartanUI\modules\UnitFrames\Options-Options.lua:1880: attempt to index global 'filters' (a nil value)
[string "@Interface\AddOns\Bartender4\libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1144: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1117>
[string "@Interface\AddOns\Bartender4\libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1648: in function `FeedGroup'
[string "@Interface\AddOns\Bartender4\libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1573: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1557>
[string "=[C]"]: ?
[string "@Interface\AddOns\Bartender4\libs\AceGUI-3.0\AceGUI-3.0.lua"]:72: in function <...ace\AddOns\Bartender4\libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Interface\AddOns\Bartender4\libs\AceGUI-3.0\AceGUI-3.0.lua"]:306: in function `Fire'
[string "@Interface\AddOns\Bartender4\libs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua"]:526: in function `Select'
[string "@Interface\AddOns\Bartender4\libs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua"]:534: in function `SelectByValue'
[string "@Interface\AddOns\Bartender4\libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1744: in function `FeedGroup'
[string "@Interface\AddOns\Bartender4\libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1573: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1557>
[string "=[C]"]: ?
[string "@Interface\AddOns\Bartender4\libs\AceGUI-3.0\AceGUI-3.0.lua"]:72: in function <...ace\AddOns\Bartender4\libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Interface\AddOns\Bartender4\libs\AceGUI-3.0\AceGUI-3.0.lua"]:306: in function `Fire'
[string "@Interface\AddOns\Bartender4\libs\AceGUI-3.0\widgets\AceGUIContainer-TabGroup.lua"]:156: in function `SelectTab'
[string "@Interface\AddOns\Bartender4\libs\AceGUI-3.0\widgets\AceGUIContainer-TabGroup.lua"]:67: in function <...libs\AceGUI-3.0\widgets\AceGUIContainer-TabGroup.lua:64>

Locals: <none>

SUI and Bartender are up to most current versions.

**Comment by siberia60** [comment] 2020-10-15 19:50
In adition.

Chatbox dosn't remember settings. (Transparency and font size.)

**Comment by Wutname1** [comment] 2020-10-15 20:30
> Message: ...face\AddOns\SpartanUI\modules\UnitFrames\Options-Options.lua:1880: attempt to index global 'filters' (a nil value)

The error will be fixed in 608 but buff settings are not finished yet. I am going to get the classic artwork in place so i stop getting as many messages first.

**Comment by Wutname1** [comment] 2020-10-15 20:30
> Chatbox dosn't remember settings. (Transparency and font size.)

You need to change it in SUI settings not via blizzard.

**Comment by Wutname1** [comment] 2020-10-15 20:31
> 5\. Zone ability / special ability button movers don't move the buttons. Even if I do drag them off the middle of the map, the buttons will apear still there.

Old bug should not be a issue since 604 (i think)

**Comment by Yojimbo789** [comment] 2020-10-16 00:01
Yea an expac comes out and your working on classic great job we'll wait no worries take all the time on old content forget the new expac.

**Comment by Awwchit** [comment] 2020-10-16 00:18
I actually created an account to post this. lol.

He is refering the to Classic Artwork. The gray Player frame etc. NOT Classic wow vs. Retail.

**Comment by Yojimbo789** [comment] 2020-10-16 00:24
Yea forget it ill tough it out with Elvui or something else. The Cosmetic that's in your face like having the player frame not match the artwork is just plain dumb not to fix. Thats retail the new expac the one that Blizzard spent millions on and delayed to make it better but no go work on Classic WoW.

**Comment by Ryzael75** [comment] 2020-10-16 04:16
Hey dumbass learn to read. Wutname1 is working on the Classic Unitframes for the Classic Artwork for the RETAIL version. He never said anything about working on the Classic version of SUI. He is working on exactly what you are complaining about. People like you are why many addon authors say to hell with it and quit producing/maintaining addons for the public.

**Comment by Wutname1** [comment] 2020-10-17 06:12
> * Quest Module.
>   The "Hide in combat" function dosn't work. The quest objective tracker is still visible even if the settings are corectly done.
> *

What are your settings exactly? Can you post a screenshot?  I just set mine to all the time when in combat and it hid when i went to hit a training dummy.

**Comment by Yojimbo789** [comment] 2020-10-17 14:55
@Ryzael75 Another update another day it aint fixed and I'm the dumbass. unit frame artwork still wont change with panel artwork. Looks out of wack since prepatch. How long people gotta stare at that. Just me but if my dvd player falls off my entertaintment center and its cracked all to hell but still plays dvds do i still want to see it like that in my living room . fix it already.

**Comment by Ryzael75** [comment] 2020-10-17 17:53
Where do you get off making demands and just plain being an ass? Most addon authors don't make a dime from their work. They don't have to release their addons or make updates. And they certainly don't have to do things on YOUR timeframe. Coding and gfx work takes time. You don't like it, then go use some other addon. For your information, it is taking so long because much of the addon is a rewrite...not a simple update.

**Comment by Yojimbo789** [comment] 2020-10-17 18:01
@Ryzael75 4.1 million downloads tells me I can buddy. unit frame is fucked how the hell you cant just fix it . As soon as you pop in in game in glaring you right in the face asshat. And if they cant handle that in a timely fashion stop working on it and as far as not making a dime he does have patrons just not me because he cant handle fixing a cosmetic issue you see as soon as you login not all the bugs behind the scenes you see that idiot.

**Comment by Wutname1** [comment] 2020-10-17 18:34
Don't need his complaining that is not contributing to anything filling my email and wasting my time.

**Comment by Wutname1** [comment] 2020-10-17 18:36
@siberia60 pleas let me know about the Quest Module stuff i commented about above. (Or anyone who can reproduce) ill be closing this in a day or 2 otherwise. You are always welcome to open a new issue with the above details.

**Comment by Ryzael75** [comment] 2020-10-17 18:59
@siberia60 As far as the quest module is concerned, let me ask a quick question. Are you using any other quest addon? I use Dugi's Questing Essentials for other features other than quest tracker...along with a ton of other addons. I had same issue as you back when I first started using Dugi's, objective tracker not hiding in combat. Come to find out I had missed a couple settings in Dugi's, 1 of which was overriding the hide function. So, if you are using another quest addon it is possible they are conflicting.

**Closed** 2020-10-19 20:14 UTC
Labels: Need more info

**Comment by siberia60** [comment] 2020-10-22 13:09
Hey.

Not using any other quest addons.

But the issue seems to be fixed, so it's all right.

If it reccurs, I'll let you know.
